# Copyright (c) 2026 Peters Digital
# SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-Commercial
name: License Header Check

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          fetch-depth: 1

      - name: Check License Headers
        run: |
          chmod +x ./scripts/check_license_headers.sh
          ./scripts/check_license_headers.sh
